# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake28

# The command to remove a file.
RM = /usr/bin/cmake28 -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake28

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/srunyon/workStuff/CVRPlugins

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/srunyon/workStuff/CVRPlugins

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake28 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake28 -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake28 -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake28 -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: install/local
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake28 -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: install/strip
.PHONY : install/strip/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake28 -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	cd /home/srunyon/workStuff/CVRPlugins && $(CMAKE_COMMAND) -E cmake_progress_start /home/srunyon/workStuff/CVRPlugins/CMakeFiles /home/srunyon/workStuff/CVRPlugins/calit2/WaterMaze/CMakeFiles/progress.marks
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/WaterMaze/all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/srunyon/workStuff/CVRPlugins/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/WaterMaze/clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/WaterMaze/preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/WaterMaze/preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	cd /home/srunyon/workStuff/CVRPlugins && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

# Convenience name for target.
calit2/WaterMaze/CMakeFiles/WaterMaze.dir/rule:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f CMakeFiles/Makefile2 calit2/WaterMaze/CMakeFiles/WaterMaze.dir/rule
.PHONY : calit2/WaterMaze/CMakeFiles/WaterMaze.dir/rule

# Convenience name for target.
WaterMaze: calit2/WaterMaze/CMakeFiles/WaterMaze.dir/rule
.PHONY : WaterMaze

# fast build rule for target.
WaterMaze/fast:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build
.PHONY : WaterMaze/fast

Controller/OutboundPacket.o: Controller/OutboundPacket.cpp.o
.PHONY : Controller/OutboundPacket.o

# target to build an object file
Controller/OutboundPacket.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/OutboundPacket.cpp.o
.PHONY : Controller/OutboundPacket.cpp.o

Controller/OutboundPacket.i: Controller/OutboundPacket.cpp.i
.PHONY : Controller/OutboundPacket.i

# target to preprocess a source file
Controller/OutboundPacket.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/OutboundPacket.cpp.i
.PHONY : Controller/OutboundPacket.cpp.i

Controller/OutboundPacket.s: Controller/OutboundPacket.cpp.s
.PHONY : Controller/OutboundPacket.s

# target to generate assembly for a file
Controller/OutboundPacket.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/OutboundPacket.cpp.s
.PHONY : Controller/OutboundPacket.cpp.s

Controller/StateUpdate.o: Controller/StateUpdate.cpp.o
.PHONY : Controller/StateUpdate.o

# target to build an object file
Controller/StateUpdate.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/StateUpdate.cpp.o
.PHONY : Controller/StateUpdate.cpp.o

Controller/StateUpdate.i: Controller/StateUpdate.cpp.i
.PHONY : Controller/StateUpdate.i

# target to preprocess a source file
Controller/StateUpdate.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/StateUpdate.cpp.i
.PHONY : Controller/StateUpdate.cpp.i

Controller/StateUpdate.s: Controller/StateUpdate.cpp.s
.PHONY : Controller/StateUpdate.s

# target to generate assembly for a file
Controller/StateUpdate.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/StateUpdate.cpp.s
.PHONY : Controller/StateUpdate.cpp.s

Controller/TrialSetup.o: Controller/TrialSetup.cpp.o
.PHONY : Controller/TrialSetup.o

# target to build an object file
Controller/TrialSetup.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/TrialSetup.cpp.o
.PHONY : Controller/TrialSetup.cpp.o

Controller/TrialSetup.i: Controller/TrialSetup.cpp.i
.PHONY : Controller/TrialSetup.i

# target to preprocess a source file
Controller/TrialSetup.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/TrialSetup.cpp.i
.PHONY : Controller/TrialSetup.cpp.i

Controller/TrialSetup.s: Controller/TrialSetup.cpp.s
.PHONY : Controller/TrialSetup.s

# target to generate assembly for a file
Controller/TrialSetup.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/TrialSetup.cpp.s
.PHONY : Controller/TrialSetup.cpp.s

Controller/WMController.o: Controller/WMController.cpp.o
.PHONY : Controller/WMController.o

# target to build an object file
Controller/WMController.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/WMController.cpp.o
.PHONY : Controller/WMController.cpp.o

Controller/WMController.i: Controller/WMController.cpp.i
.PHONY : Controller/WMController.i

# target to preprocess a source file
Controller/WMController.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/WMController.cpp.i
.PHONY : Controller/WMController.cpp.i

Controller/WMController.s: Controller/WMController.cpp.s
.PHONY : Controller/WMController.s

# target to generate assembly for a file
Controller/WMController.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Controller/WMController.cpp.s
.PHONY : Controller/WMController.cpp.s

Cue.o: Cue.cpp.o
.PHONY : Cue.o

# target to build an object file
Cue.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Cue.cpp.o
.PHONY : Cue.cpp.o

Cue.i: Cue.cpp.i
.PHONY : Cue.i

# target to preprocess a source file
Cue.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Cue.cpp.i
.PHONY : Cue.cpp.i

Cue.s: Cue.cpp.s
.PHONY : Cue.s

# target to generate assembly for a file
Cue.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Cue.cpp.s
.PHONY : Cue.cpp.s

Experiment.o: Experiment.cpp.o
.PHONY : Experiment.o

# target to build an object file
Experiment.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Experiment.cpp.o
.PHONY : Experiment.cpp.o

Experiment.i: Experiment.cpp.i
.PHONY : Experiment.i

# target to preprocess a source file
Experiment.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Experiment.cpp.i
.PHONY : Experiment.cpp.i

Experiment.s: Experiment.cpp.s
.PHONY : Experiment.s

# target to generate assembly for a file
Experiment.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Experiment.cpp.s
.PHONY : Experiment.cpp.s

EyeData.o: EyeData.cpp.o
.PHONY : EyeData.o

# target to build an object file
EyeData.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/EyeData.cpp.o
.PHONY : EyeData.cpp.o

EyeData.i: EyeData.cpp.i
.PHONY : EyeData.i

# target to preprocess a source file
EyeData.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/EyeData.cpp.i
.PHONY : EyeData.cpp.i

EyeData.s: EyeData.cpp.s
.PHONY : EyeData.s

# target to generate assembly for a file
EyeData.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/EyeData.cpp.s
.PHONY : EyeData.cpp.s

Paradigm.o: Paradigm.cpp.o
.PHONY : Paradigm.o

# target to build an object file
Paradigm.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Paradigm.cpp.o
.PHONY : Paradigm.cpp.o

Paradigm.i: Paradigm.cpp.i
.PHONY : Paradigm.i

# target to preprocess a source file
Paradigm.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Paradigm.cpp.i
.PHONY : Paradigm.cpp.i

Paradigm.s: Paradigm.cpp.s
.PHONY : Paradigm.s

# target to generate assembly for a file
Paradigm.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Paradigm.cpp.s
.PHONY : Paradigm.cpp.s

Path.o: Path.cpp.o
.PHONY : Path.o

# target to build an object file
Path.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Path.cpp.o
.PHONY : Path.cpp.o

Path.i: Path.cpp.i
.PHONY : Path.i

# target to preprocess a source file
Path.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Path.cpp.i
.PHONY : Path.cpp.i

Path.s: Path.cpp.s
.PHONY : Path.s

# target to generate assembly for a file
Path.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/Path.cpp.s
.PHONY : Path.cpp.s

PathData.o: PathData.cpp.o
.PHONY : PathData.o

# target to build an object file
PathData.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/PathData.cpp.o
.PHONY : PathData.cpp.o

PathData.i: PathData.cpp.i
.PHONY : PathData.i

# target to preprocess a source file
PathData.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/PathData.cpp.i
.PHONY : PathData.cpp.i

PathData.s: PathData.cpp.s
.PHONY : PathData.s

# target to generate assembly for a file
PathData.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/PathData.cpp.s
.PHONY : PathData.cpp.s

WaterMaze.o: WaterMaze.cpp.o
.PHONY : WaterMaze.o

# target to build an object file
WaterMaze.cpp.o:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/WaterMaze.cpp.o
.PHONY : WaterMaze.cpp.o

WaterMaze.i: WaterMaze.cpp.i
.PHONY : WaterMaze.i

# target to preprocess a source file
WaterMaze.cpp.i:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/WaterMaze.cpp.i
.PHONY : WaterMaze.cpp.i

WaterMaze.s: WaterMaze.cpp.s
.PHONY : WaterMaze.s

# target to generate assembly for a file
WaterMaze.cpp.s:
	cd /home/srunyon/workStuff/CVRPlugins && $(MAKE) -f calit2/WaterMaze/CMakeFiles/WaterMaze.dir/build.make calit2/WaterMaze/CMakeFiles/WaterMaze.dir/WaterMaze.cpp.s
.PHONY : WaterMaze.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... WaterMaze"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... Controller/OutboundPacket.o"
	@echo "... Controller/OutboundPacket.i"
	@echo "... Controller/OutboundPacket.s"
	@echo "... Controller/StateUpdate.o"
	@echo "... Controller/StateUpdate.i"
	@echo "... Controller/StateUpdate.s"
	@echo "... Controller/TrialSetup.o"
	@echo "... Controller/TrialSetup.i"
	@echo "... Controller/TrialSetup.s"
	@echo "... Controller/WMController.o"
	@echo "... Controller/WMController.i"
	@echo "... Controller/WMController.s"
	@echo "... Cue.o"
	@echo "... Cue.i"
	@echo "... Cue.s"
	@echo "... Experiment.o"
	@echo "... Experiment.i"
	@echo "... Experiment.s"
	@echo "... EyeData.o"
	@echo "... EyeData.i"
	@echo "... EyeData.s"
	@echo "... Paradigm.o"
	@echo "... Paradigm.i"
	@echo "... Paradigm.s"
	@echo "... Path.o"
	@echo "... Path.i"
	@echo "... Path.s"
	@echo "... PathData.o"
	@echo "... PathData.i"
	@echo "... PathData.s"
	@echo "... WaterMaze.o"
	@echo "... WaterMaze.i"
	@echo "... WaterMaze.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	cd /home/srunyon/workStuff/CVRPlugins && $(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

